### ISSUE TITLE
Figure out checking if given hardware ID is available to use

### ISSUE THREAD

**Issue by invidian** [tinkerbell/cluster-api-provider-tink#15]
Right now we ask user to select hardware IDs which should be used for nodes, but we could as well pick any available hardware from Tinkerbell server. In both cases, we need to check if given hardware is ready to run workflows. The easiest way of doing this is just to see if there are any workflows associated with a given hardware.

**Comment by gianarb** [comment]
I think @mmlb and @splaspood @markyjackson-taulia can give us an idea about this.

> we need to check if the given hardware is ready to run workflows.

In practice, we have to identify if give hardware can be a good candidate for provisioning. I think using the previous workflow is an easy way to do it and it will work for `v0.1.0` but moving forward we will have to use a combination of factors.

For not it works mainly because deprovisioning and machine update won't be supported in `v0.1.0`

**Comment by invidian** [comment]
Something like this works fine: https://github.com/tinkerbell/cluster-api-provider-tink/blob/b3153920195a2dbdbfe70271f958aaac508b178e/controllers/tinkerbell.go#L128-L216.

**Comment by invidian** [comment]
Note, that code above is vulnerable to TOCTOU. In the future we should have some sort of locking mechanism, which will allow us to reserve hardware for a given cluster.

**Comment by gianarb** [comment]
> Note, that code above is vulnerable to TOCTOU. In the future we should have some sort of locking mechanism, which will allow us to reserve hardware for a given cluster.

I still think we should specify a list of hardware ID because I don't want to use all my 10 NUCs for ClusterAPI :P but yes! We also need something smarter than a list! xD

**Comment by invidian** [comment]
I'm reworking #17 right now to make it based on #8, so we can use most likely labels to figure out if hardware is available.
